[package]
name = "try-serverless-framework-rust"
version = "0.1.0"
authors = ["Greg Wiley <gwiley@cj.com>"]
edition = "2018"

[dependencies]
lambda_runtime = "0.2"
serde = "^1"
serde_derive = "^1"
log = "^0.4"
simple_logger = "^1"

